name: Fly Deploy

on:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_ORGANIZATION: ${{ secrets.FLY_ORGANIZATION }}